#! /usr/bin/python3

# SCsub

Import('env')

module_env = env.Clone()
module_env.disable_warnings()
# OGG support
module_env.Append(CPPPATH=["libogg/include"])
module_env.Append(CPPPATH=["libvorbis/include"])
# pxtone
module_env.add_source_files(env.modules_sources, "./pxtone/*.cpp")
module_env.add_source_files(env.modules_sources, "*.cpp")
module_env.Append(CPPDEFINES=['_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES']) # The pxtone source code won't compile if this is not defined.
module_env.Append(CPPDEFINES=['pxINCLUDE_OGGVORBIS'])
